### ISSUE TITLE
Has problem with "playtest.py"

### ISSUE THREAD

**Issue by Graceliying82** [adafruit/Adafruit_Python_MPR121#4]
I am using Capacitive Touch Sensor Hat.

I ran playtest.py on my Raspberry Pi. When I touched the board directly, it worked OK. But once I connect the alligator clips to the board, it didn't work properly. I tried every pins. Only one pair worked.
I compared the working ones with the non-working ones, I found the reason is that the pins not "released" even when I didn't touch it. 
Could you give me some advice on how to solve the problem.

BTW,I googled the issue. Some people suggest change the touch threshold. I checked Adafruit-mpr121 documents. It mentioned a function setThreshholds(). However, when I tried:
"cap.setThresholds(12, 8)", I got an error :"‘MPR121' object has no attribute 'setThreshholds".
I also tried set_threshold() as some article suggested. It didn't work either.

Would you help to advice. Thanks!

**Comment by FellerAilton** [comment]
The same was happening to me, then reading and exploring the examples, i made this code, to make some kind of filter and then it just detects when it's really touched, giving no false positives. Sorry for the bad english, and the code is python 2.7, but you know, to make it 3.5 just put the parenthesis on the print :)

```
filtered_touch = int(cap.filtered_data(2))
base_touch_real = int(cap.baseline_data(2))
base_touch_filtered = base_touch_real - (base_touch_real*0.3)
if (filtered_touch < (base_touch_filtered)):
    print 'Pin 2 is being touched!'
```

**Comment by kattni** [comment]
Hello, please submit your question to the [Adafruit Forums](https://forums.adafruit.com) to receive assistance.

This library is no longer supported. We are only supporting the use of CircuitPython libraries through [Adafruit Blinka](https://github.com/adafruit/Adafruit_Blinka). Please see the [Adafruit CircuitPython MPR121 library](https://github.com/adafruit/Adafruit_CircuitPython_MPR121).
