### ISSUE TITLE
/opt/sonic-pi/etc/samples/ are now .flac and some work but most dont

### ISSUE THREAD

**Issue by y0uki11edkenny** [adafruit/Adafruit_Python_MPR121#8]
I went to the samples folder and found that the files are now .flacs not .wav and I have had issues with some where some .flac work but most don't. Also Mp3 files under media sounds dont work under with the raspbian Pixel.

# Define mapping of capacitive touch pin presses to sound files
# tons more sounds are available in /opt/sonic-pi/etc/samples/ and
# /usr/share/scratch/Media/Sounds/
SOUND_MAPPING = {
  0: '/opt/sonic-pi/etc/samples/drum_bass_soft.wav',
  1: '/opt/sonic-pi/etc/samples/drum_bass_hard.wav',
  2: '/opt/sonic-pi/etc/samples/drum_snare_soft.wav',
  3: '/opt/sonic-pi/etc/samples/drum_snare_hard.wav',
  4: '/opt/sonic-pi/etc/samples/drum_tom_lo_soft.wav',
  5: '/opt/sonic-pi/etc/samples/drum_tom_mid_hard.wav',
  6: '/opt/sonic-pi/etc/samples/drum_tom_hi_hard.wav',
  7: '/opt/sonic-pi/etc/samples/drum_heavy_kick.wav',
  8: '/opt/sonic-pi/etc/samples/drum_cymbal_open.wav',
  9: '/opt/sonic-pi/etc/samples/drum_cymbal_hard.wav',
  10: '/opt/sonic-pi/etc/samples/drum_cymbal_soft.wav',
  11: '/opt/sonic-pi/etc/samples/perc_bell.wav',

**Comment by ladyada** [comment]
ohh - thats annoying! do you mind submitting a pull request with the new file locations?

**Comment by y0uki11edkenny** [comment]
I have changed the files to animal sounds because it had 12 wav files in that folder and submitted a pull request.

**Comment by ladyada** [comment]
thanks you :)

**Comment by y0uki11edkenny** [comment]
no problem

Regards,
Kenny Lilly
Ph:720-938-0143
Email: Lilly.kenny@gmail.com
Linkedin Profile: http://www.linkedin.com/in/lillykenny
